In [1]:
import json

import pandas as pd

with open("2024學年度_10411-03-01-2_臺中市高級中等學校外國學生數.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

In [2]:
df = pd.DataFrame(data=data)

In [3]:
df.head(5)

,地區,項目,欄位名稱,數值,資料時間日期,資料週期,郵遞區號,機關代碼,電子郵件,行動電話,市話,縣市別代碼,行政區域代碼
0,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_一年級_男,2,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
1,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_一年級_女,0,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
2,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_二年級_男,2,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
3,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_二年級_女,0,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
4,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_三年級_男,0,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000

In [4]:
df.dtypes

地區        object
項目        object
欄位名稱      object
數值        object
資料時間日期    object
資料週期      object
郵遞區號      object
機關代碼      object
電子郵件      object
行動電話      object
市話        object
縣市別代碼     object
行政區域代碼    object
dtype: object

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   地區      80 non-null     object
 1   項目      80 non-null     object
 2   欄位名稱    80 non-null     object
 3   數值      80 non-null     object
 4   資料時間日期  80 non-null     object
 5   資料週期    80 non-null     object
 6   郵遞區號    80 non-null     object
 7   機關代碼    80 non-null     object
 8   電子郵件    80 non-null     object
 9   行動電話    80 non-null     object
 10  市話      80 non-null     object
 11  縣市別代碼   80 non-null     object
 12  行政區域代碼  80 non-null     object
dtypes: object(13)
memory usage: 8.2+ KB

In [6]:
df.head(5)

,地區,項目,欄位名稱,數值,資料時間日期,資料週期,郵遞區號,機關代碼,電子郵件,行動電話,市話,縣市別代碼,行政區域代碼
0,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_一年級_男,2,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
1,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_一年級_女,0,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
2,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_二年級_男,2,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
3,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_二年級_女,0,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000
4,臺中市,臺中市高級中等學校外國學生數-學生數(單位:人),美國_高級中等學校_三年級_男,0,2024-08-01T00:00:00,學年,407610,387000000A,oddisp@taichung.gov.tw,0910289111,(04)22289111,66000,10019000

In [7]:
df.to_csv("測試.csv")

In [8]:
from langchain_core.prompts.image import ImagePromptTemplate
from langchain_core.prompts import ChatPromptTemplate, SystemMessagePromptTemplate, HumanMessagePromptTemplate, PromptTemplate


def build_standard_chat_prompt_template(kwargs):
    """Build a ChatPromptTemplate from system and human message configs.

    Supports both text-only and multimodal (text + image) prompts.

    Args:
        kwargs: Dictionary with optional 'system' and 'human' keys.
            Each value is a dict with 'template' (required) and optional
            'type' ('text' or 'image') and 'input_variables'.

    Returns:
        A configured ChatPromptTemplate ready for use with an LLM.
    """
    messages = []

    if 'system' in kwargs:
        content = kwargs.get('system')

        # allow list of prompts for multimodal
        if isinstance(content, list):
            prompts = [PromptTemplate(**c) for c in content]
        else:
            prompts = [PromptTemplate(**content)]

        message = SystemMessagePromptTemplate(prompt=prompts)
        messages.append(message)

    if 'human' in kwargs:
        content = kwargs.get('human')

        # allow list of prompts for multimodal
        if isinstance(content, list):
            prompts = []
            for c in content:
                if c.get("type") == "image":
                    prompts.append(ImagePromptTemplate(**c))
                else:
                    prompts.append(PromptTemplate(**c))
        else:
            if content.get("type") == "image":
                prompts = [ImagePromptTemplate(**content)]
            else:
                prompts = [PromptTemplate(**content)]

        message = HumanMessagePromptTemplate(prompt=prompts)
        messages.append(message)

    chat_prompt_template = ChatPromptTemplate.from_messages(messages)

    return chat_prompt_template

C:\Users\Ling\miniconda3\envs\aicg\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
df.to_csv("測試.csv")

建立工具: Schema Tool

In [10]:
import io
import os
from contextlib import redirect_stdout
from pydantic import BaseModel, Field
from textwrap import dedent


from langchain.tools import BaseTool, ToolRuntime
from langchain_core.output_parsers import PydanticOutputParser, StrOutputParser
from langchain_core.runnables import Runnable


class Context(BaseModel):
    directory: str
    schema_output: str = ""


SCHEMA_SYSTEM_PROMPT = dedent("""
# Role
你是一位專業的 Python 資料分析師，精通 pandas 資料處理。你的任務是為指定的 CSV 檔案生成精確、可執行的 Python 代碼。

# Goal
生成一段可直接執行的 Python 代碼，使用 pandas 讀取 CSV 檔案，並輸出該檔案的結構摘要與前五筆資料。

# Input
- <file>: 待分析的 CSV 檔案完整路徑

# Rule
- 使用 `pd.read_csv()` 讀取 CSV 檔案，指定 `encoding='utf-8'`
- 使用 `df.info()` 輸出人類可讀的完整摘要（欄位名、非空值數量、資料型別）
- 使用 `print(df.head(5).to_string())` 輸出前五筆資料
- 輸出的代碼必須是純 Python 代碼，不含任何 markdown 標記或解釋文字

# Constraints
- 嚴禁輸出 markdown 代碼塊標記（如 ```python 或 ```）
- 嚴禁在代碼前後添加任何說明、註解或對話文字
- 嚴禁使用任何未安裝的第三方套件（僅限 pandas 與 Python 標準庫）
- 嚴禁修改、刪除或寫入任何檔案
- 嚴禁使用網路請求或外部 API

# Reasoning (Chain of Thought)
請依以下步驟逐步推理，每完成一步再進行下一步：

Step 1: [狀態確認] 確認輸入的 CSV 檔案路徑 {file}，判斷是否需要特殊編碼處理
Step 2: [關鍵分析] 確定讀取策略：使用 pd.read_csv()，設定適當的 encoding 參數
Step 3: [推理展開] 構建輸出邏輯：先呼叫 df.info() 輸出結構摘要，再呼叫 print(df.head(5).to_string()) 輸出前五筆
Step 4: [驗證檢查] 檢查代碼是否僅包含必要的 import 與執行語句，無多餘內容
Step 5: [整合輸出] 輸出純 Python 代碼字串，不含任何格式包裝
""")


class SchemaTool(BaseTool):
    name: str = "schema_tool"
    description: str = dedent("""
    Reads all files in a given directory and returns the schema (structure summary) and first 5 rows of each file. Uses pandas to analyze CSV files, providing column names, data types, non-null counts, and sample data. Use this tool when you need to understand the structure and content of data files before further processing.
    """)

    pipeline: Runnable

    @classmethod
    def create(cls, llm: Runnable):

        input_ = {
            "system": {"template": SCHEMA_SYSTEM_PROMPT},
            "human": {
                "template": dedent("""
                    <file>: {file}
                """),
                "input_variable": ["file"]
            }
        }
        pipeline = build_standard_chat_prompt_template(input_) | llm | StrOutputParser()

        return cls(pipeline=pipeline)

    def _run(self, runtime: ToolRuntime[Context], **input):

        directory = runtime.context.directory
    
        raw_output = ""
        
        for f in os.listdir(directory):
            
            if not f.endswith(".csv"):
                continue
                
            file = os.path.join(directory, f)
            
            code = self.pipeline.invoke({
                "file": file
            })
    
            stdout_capture = io.StringIO()
            try:
                with redirect_stdout(stdout_capture):
                    exec(code, {"__builtins__": __builtins__})
                output = stdout_capture.getvalue()
            except Exception as e:
                output = f"EXECUTION ERROR: {str(e)}"

            raw_output += f"-{file}: {output}\n\n"

        # 將 數據的 schema 送入context中
        runtime.context.schema_output = raw_output
            
        return raw_output

    async def _arun(self, runtime: ToolRuntime[Context]):

        return "Not implemented Yet"

In [11]:
from langchain.agents import create_agent
from langchain_ollama import ChatOllama
from langchain.agents.middleware.tool_retry import ToolRetryMiddleware
from langchain.agents.middleware.tool_call_limit import ToolCallLimitMiddleware
from langchain_core.messages import HumanMessage


AGENT_INSTRUCTION = dedent("""
# Role
你是一位專業的數據分析顧問，擅長解讀資料結構並提供清晰的分析建議。你的工作方式是先了解資料的樣貌，再根據使用者需求給出精準的回應。

# Goal
協助使用者理解資料內容並回答數據分析相關問題。

# Tool
你可以使用以下工具來完成任務：

- **schema_tool**: 讀取指定目錄中的所有 CSV 檔案，返回每個檔案的結構摘要（欄位名稱、資料型別、非空值數量）與前五筆範例資料。適用於需要了解資料結構與內容的場景。

# Input
使用者會以自然語言描述他們的數據分析需求或問題。

# Rule
- 當使用者詢問關於資料檔案的內容、結構或分析建議時，先調用工具獲取資料資訊
- 根據工具返回的結構摘要與前五筆資料，解讀每個欄位的意義與資料型別
- 針對使用者的具體問題，基於實際的資料結構給出分析建議或答案
- 若工具返回錯誤，如實告知使用者並建議檢查檔案格式

# Constraints
- 嚴禁在未調用工具的情況下憑空猜測資料內容
- 嚴禁對資料進行任何寫入、修改或刪除操作
- 回答必須基於工具返回的實際資料，不得虛構

# Reasoning (ReAct)
使用 ReAct（Reasoning + Acting）框架，在「推理」與「行動」之間交替進行：

Thought: 分析使用者需求，判斷是否需要調用工具，以及需要哪些資訊
Action: 選擇並調用合適的工具，傳入必要參數
Observation: 仔細觀察工具返回的結果，提取關鍵資訊
Thought: 根據觀察結果進行分析推理，判斷是否需要進一步行動
...（重複 Thought → Action → Observation 循環，直到足以回答問題）
Final Answer: 給出清晰、有條理的最終回答
""")


llm = ChatOllama(model='deepseek-v4-pro:cloud',
                 base_url='https://ollama.com',
                 name='main', temperature=0)


tools = [SchemaTool.create(llm=llm)]

agent = create_agent(
    model=llm,
    name="analysis_agent",
    tools=tools,
    system_prompt=AGENT_INSTRUCTION,
    middleware=[
        ToolRetryMiddleware(max_retries=2),
        ToolCallLimitMiddleware(exit_behavior='end',
                                run_limit=1,
                                tool_name="schema_tool")
    ]
)

In [12]:
context = Context(directory="./")

In [13]:
agent_input = {"messages": HumanMessage(content="顯示所有檔案的schema")}

In [14]:
for update in agent.stream(
    agent_input,
    context=context,
    stream_mode="updates",
):
    # 只保留 model 和 tool 兩個 key
    for key, value in update.items():
        if key == "model":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].tool_calls)
        if key == "tools":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].name)

model:   [{'name': 'schema_tool', 'args': {'input': {}}, 'id': '49d991d2-4573-410f-b88f-de0566b57f90', 'type': 'tool_call'}]
tools:  -./測試.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  80 non-null     int64
 1   地區          80 non-null     object
 2   項目          80 non-null     object
 3   欄位名稱        80 non-null     object
 4   數值          80 non-null     int64
 5   資料時間日期      80 non-null     object
 6   資料週期        80 non-null     object
 7   郵遞區號        80 non-null     int64
 8   機關代碼        80 non-null     object
 9   電子郵件        80 non-null     object
 10  行動電話        80 non-null     int64
 11  市話          80 non-null     object
 12  縣市別代碼       80 non-null     int64
 13  行政區域代碼      80 non-null     int64
dtypes: int64(6), object(8)
memory usage: 8.9+ KB
   Unnamed: 0   地區                        項目             欄位名稱  數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_一年級_男   2  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_一年級_女   0  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_二年級_男   2  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_二年級_女   0  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_三年級_男   0  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


 schema_tool
model:  ## 📊 資料結構摘要

目前目錄中僅有一個檔案：**`測試.csv`**

---

### 檔案：`測試.csv`

| 屬性 | 內容 |
|------|------|
| 總筆數 | 80 筆 |
| 總欄位數 | 14 欄 |

---

### 欄位結構

| # | 欄位名稱 | 資料型別 | 非空值數量 | 說明（推測） |
|---|---------|---------|-----------|-------------|
| 0 | `Unnamed: 0` | int64 | 80 | 原始索引欄位（可能是匯出時產生的流水號） |
| 1 | `地區` | object | 80 | 地區名稱，如「臺中市」 |
| 2 | `項目` | object | 80 | 統計項目名稱，如「臺中市高級中等學校外國學生數-學生數(單位:人)」 |
| 3 | `欄位名稱` | object | 80 | 細項分類，包含國家、年級、性別等維度，如「美國_高級中等學校_一年級_男」 |
| 4 | `數值` | int64 | 80 | 統計數值（單位：人） |
| 5 | `資料時間日期` | object | 80 | 資料時間，格式為 `YYYY-MM-DDT00:00:00`（如 2024-08-01） |
| 6 | `資料週期` | object | 80 | 資料週期類型，如「學年」 |
| 7 | `郵遞區號` | int64 | 80 | 郵遞區號（如 407610） |
| 8 | `機關代碼` | object | 80 | 政府機關代碼（如 387000000A） |
| 9 | `電子郵件` | object | 80 | 聯絡電子郵件 |
| 10 | `行動電話` | int64 | 80 | 行動電話號碼 |
| 11 | `市話` | object | 80 | 市內電話號碼 |
| 12 | `縣市別代碼` | int64 | 80 | 縣市代碼（如 66000 代表臺中市） |
| 13 | `行政區域代碼` | int64 | 80 | 行政區域代碼（如 10019000） |

---

### 前五筆範例資料

| 地區 | 項目 | 欄位名稱 | 數值 | 資料時間日期 | 資料週期 |
|------|------|---------|------|-------------|---------|
| 臺中市 | 臺中市高級中等學校外國學生數-學生數(單位:人) | 美國_高級中等學校_一年級_男 | 2 | 2024-08-01 | 學年 |
| 臺中市 | 臺中市高級中等學校外國學生數-學生數(單位:人) | 美國_高級中等學校_一年級_女 | 0 | 2024-08-01 | 學年 |
| 臺中市 | 臺中市高級中等學校外國學生數-學生數(單位:人) | 美國_高級中等學校_二年級_男 | 2 | 2024-08-01 | 學年 |
| 臺中市 | 臺中市高級中等學校外國學生數-學生數(單位:人) | 美國_高級中等學校_二年級_女 | 0 | 2024-08-01 | 學年 |
| 臺中市 | 臺中市高級中等學校外國學生數-學生數(單位:人) | 美國_高級中等學校_三年級_男 | 0 | 2024-08-01 | 學年 |

---

### 🔍 初步觀察

1. **資料主題**：此資料集記錄的是 **臺中市高級中等學校外國學生數**，以學年為週期，按國家、年級、性別進行分類統計。
2. **欄位名稱結構**：`欄位名稱` 採用底線分隔格式，包含「國家_學校層級_年級_性別」等維度資訊，可考慮拆分成多個獨立欄位以便分析。
3. **聯絡資訊**：`電子郵件`、`行動電話`、`市話`、`機關代碼` 等欄位在整份資料中似乎是常數值，可能為資料提供單位的聯絡資訊。
4. **數值範圍**：`數值`欄位多為 0 或小數值，符合外國學生人數較少的實際情況。

---

請問您需要針對這份資料進行什麼樣的分析呢？ []

Pandas Tool

In [15]:
from typing import List


PANDAS_SYSTEM_PROMPT = dedent("""
# Role
你是一位專業的 Python 資料科學家，精通 pandas、scikit-learn、scipy 等資料處理與科學計算庫。你的任務是根據使用者指定的 CSV 檔案，生成精確、可執行的 Python 代碼來進行數據處理與分析。

# Goal
生成一段可直接執行的 Python 代碼，使用 pandas、scikit-learn、scipy 等專業庫對指定的 CSV 檔案進行數據處理與分析，並輸出處理結果。

# Input
- <files>: 待處理的 CSV 檔案完整路徑列表
- <context>: schema_tool 回傳的檔案結構摘要（欄位名稱、資料型別、範例資料）
- <user_query>: 使用者的原始分析需求或問題

# Rule
- 使用 `pd.read_csv()` 讀取每個 CSV 檔案，指定 `encoding='utf-8'`
- 根據 <user_query> 與 <context> 中的欄位結構，選用合適的庫進行數據處理與分析：
  - **pandas**: 資料讀取、篩選、分組、聚合、合併（`pd.merge` / `pd.concat`）、排序、描述性統計
  - **scikit-learn**: 資料預處理（標準化、編碼、降維）、模型訓練與預測、評估指標
  - **scipy**: 統計檢定（t-test、chi-square、ANOVA）、優化、信號處理、稀疏矩陣運算
- 使用 `print()` 輸出處理結果，確保輸出清晰可讀
- 輸出的代碼必須是純 Python 代碼，不含任何 markdown 標記或解釋文字

# Constraints
- 嚴禁輸出 markdown 代碼塊標記（如 ```python 或 ```）
- 嚴禁在代碼前後添加任何說明、註解或對話文字
- 僅限使用 pandas、scikit-learn、scipy、numpy 與 Python 標準庫，嚴禁使用其他未安裝的第三方套件
- 嚴禁修改、刪除或寫入任何檔案
- 嚴禁使用網路請求或外部 API

# Reasoning (Chain of Thought)
請依以下步驟逐步推理，每完成一步再進行下一步：

Step 1: [狀態確認] 確認輸入的 CSV 檔案列表 {files}，判斷檔案數量、結構與可能的關聯性
Step 2: [需求分析] 根據 <user_query> 與 <context> 中的欄位資訊，選擇最合適的庫與方法（pandas 處理 / sklearn 建模 / scipy 檢定）
Step 3: [推理展開] 構建處理流程：讀取 → 預處理 → 分析/建模 → 輸出結果
Step 4: [驗證檢查] 檢查代碼是否僅包含必要的 import 與執行語句，無多餘內容
Step 5: [整合輸出] 輸出純 Python 代碼字串，不含任何格式包裝
""")


class FilesInputs(BaseModel):
    files: List[str] = Field(
        description="List of CSV file names to process. Provide the filenames (without directory path) of the data files you want to analyze or transform.")
    user_query: str = Field(
        description="The user's original question or analysis requirement in natural language.")


class PandasTool(BaseTool):
    name: str = "pandas_tool"

    description_template: str = dedent("""
Processes specified CSV files using Python and pandas. Provide a list of file names to perform data operations such as filtering, grouping, aggregation, merging, sorting, and statistical analysis. Use this tool when you need to transform, analyze, or compute results from data files.

{input_format_instructions}
    """)

    input_parser: PydanticOutputParser = PydanticOutputParser(pydantic_object=FilesInputs)
    input_format_instructions: str = input_parser.get_format_instructions()

    description: str = description_template.format(input_format_instructions=input_format_instructions)

    pipeline: Runnable

    @classmethod
    def create(cls, llm: Runnable):

        input_ = {
            "system": {"template": PANDAS_SYSTEM_PROMPT},
            "human": {
                "template": dedent("""
                    <files>: {files}
                    <context>: {context}
                    <user_query>: {user_query}
                """),
                "input_variables": ["files", "context", "user_query"]
            }
        }
        pipeline = build_standard_chat_prompt_template(input_) | llm | StrOutputParser()

        return cls(pipeline=pipeline)

    def _run(self, runtime: ToolRuntime[Context], **input):
        directory = runtime.context.directory

        args = input.get("input", input)

        files = args['files']
        user_query = args['user_query']
        
        # Prepend cached schema output to ensure full schema info is available
        if runtime.context.schema_output:
            context = f"Schema Information:\n{runtime.context.schema_output}\n\n"

        code = self.pipeline.invoke({
            "files": [os.path.join(directory, f) for f in files],
            "context": context,
            "user_query": user_query
        })

        stdout_capture = io.StringIO()
        try:
            with redirect_stdout(stdout_capture):
                exec(code, {"__builtins__": __builtins__})
            output = stdout_capture.getvalue()
        except Exception as e:
            output = f"EXECUTION ERROR: {str(e)}"

        return output

    async def _arun(self, runtime: ToolRuntime[Context]):

        return "Not implemented Yet"

In [16]:
AGENT_INSTRUCTION_VERSION_2 = dedent("""
# Role
你是一位專業的數據分析顧問，擅長解讀資料結構並提供清晰的分析建議。你的工作方式是先了解資料的樣貌，再根據使用者需求給出精準的回應。

# Goal
協助使用者理解資料內容並回答數據分析相關問題。

# Tool
你可以使用以下工具來完成任務：

- **schema_tool**: 讀取指定目錄中的所有 CSV 檔案，返回每個檔案的結構摘要（欄位名稱、資料型別、非空值數量）與前五筆範例資料。注意：此工具僅提供結構資訊與極少量範例，無法用於統計、篩選或計算。
- **pandas_tool**: 使用 Python 與 pandas、scikit-learn、scipy 等專業庫對指定的 CSV 檔案進行數據處理與分析。支援篩選、分組、聚合、合併、統計檢定、機器學習建模等操作。這是唯一能對資料進行實際計算與分析的工具。

# Input
使用者會以自然語言描述他們的數據分析需求或問題。

# Rule
- 第一步：調用 `schema_tool` 了解有哪些檔案、每個檔案的欄位結構與資料型別
- 第二步：根據 schema_tool 返回的欄位資訊，調用 `pandas_tool` 對相關檔案進行實際的數據處理與分析
- 重要：調用 pandas_tool 時，必須將 schema_tool 的完整輸出作為 `context` 參數傳入，並將使用者的原始問題作為 `user_query` 參數傳入
- 重要：schema_tool 僅提供結構與 5 筆範例，任何涉及篩選、統計、聚合、計數、排序、建模的操作都必須透過 pandas_tool 完成
- 調用 pandas_tool 時，從 schema_tool 的結果中選取相關的檔案名稱傳入 `files` 參數
- 若工具返回錯誤，如實告知使用者並建議檢查檔案格式或需求描述

# Constraints
- 嚴禁在未調用工具的情況下憑空猜測資料內容
- 嚴禁僅憑 schema_tool 的 5 筆範例資料就回答需要統計或計算的問題
- 嚴禁對資料進行任何寫入、修改或刪除操作
- 回答必須基於 pandas_tool 的實際計算結果，不得虛構

# Reasoning (ReAct)
使用 ReAct（Reasoning + Acting）框架，在「推理」與「行動」之間交替進行：

Thought: 分析使用者需求，判斷這是否為純結構問題（只需 schema_tool）還是數據分析問題（需要 pandas_tool 進行計算）
Action: 若需要了解結構，調用 schema_tool；若需要計算分析，調用 pandas_tool
Observation: 仔細觀察工具返回的結果，提取關鍵資訊
Thought: 若已調用 schema_tool 但問題需要數據計算，則必須繼續調用 pandas_tool，不可在此停止
...（重複 Thought → Action → Observation 循環，直到足以回答問題）
Final Answer: 基於 pandas_tool 的計算結果，給出清晰、有條理的最終回答
""")


llm = ChatOllama(model='deepseek-v4-pro:cloud',
                 base_url='https://ollama.com',
                 name='main', temperature=0)


tools = [SchemaTool.create(llm=llm),
         PandasTool.create(llm=llm)]

agent = create_agent(
    model=llm,
    name="analysis_agent_version_2",
    tools=tools,
    system_prompt=AGENT_INSTRUCTION_VERSION_2,
    middleware=[
        ToolRetryMiddleware(max_retries=2),
    ]
)

In [17]:
agent_input = {"messages": HumanMessage(content="顯示外國學生數量")}
for update in agent.stream(
    agent_input,
    context=context,
    stream_mode="updates",
):
    # 只保留 model 和 tool 兩個 key
    for key, value in update.items():
        if key == "model":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].tool_calls)
        if key == "tools":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].name)

model:   [{'name': 'schema_tool', 'args': {}, 'id': 'c9ee3052-b009-45f0-bbe1-7a19ffe2bf07', 'type': 'tool_call'}]
tools:  -./測試.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  80 non-null     int64
 1   地區          80 non-null     object
 2   項目          80 non-null     object
 3   欄位名稱        80 non-null     object
 4   數值          80 non-null     int64
 5   資料時間日期      80 non-null     object
 6   資料週期        80 non-null     object
 7   郵遞區號        80 non-null     int64
 8   機關代碼        80 non-null     object
 9   電子郵件        80 non-null     object
 10  行動電話        80 non-null     int64
 11  市話          80 non-null     object
 12  縣市別代碼       80 non-null     int64
 13  行政區域代碼      80 non-null     int64
dtypes: int64(6), object(8)
memory usage: 8.9+ KB
   Unnamed: 0   地區                        項目             欄位名稱  數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_一年級_男   2  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_一年級_女   0  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_二年級_男   2  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_二年級_女   0  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  臺中市高級中等學校外國學生數-學生數(單位:人)  美國_高級中等學校_三年級_男   0  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


 schema_tool
model:   [{'name': 'pandas_tool', 'args': {'input': {'files': ['測試.csv'], 'user_query': '顯示外國學生數量的完整資料。請列出所有資料，按地區、項目、欄位名稱和數值來呈現。同時也請計算：1) 總外國學生數 2) 按國家分組的學生數 3) 按年級分組的學生數 4) 按性別分組的學生數'}}, 'id': '393b93e6-faa7-4792-ad99-6440d8c5f03c', 'type': 'tool_call'}]
tools:  完整資料：
 地區                       項目              欄位名稱  數值
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_一年級_男   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_二年級_男   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_三年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   美國_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_一年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_一年級_男   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_一年級_女   3
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_二年級_男   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_三年級_男   3
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_三年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   南韓_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_三年級_男   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_三年級_女   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   日本_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_一年級_男   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_三年級_女   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  菲律賓_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_一年級_男   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_三年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印尼_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_一年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_三年級_女   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   印度_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_一年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_二年級_男   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_二年級_女   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_三年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人) 馬來西亞_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_一年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_一年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_三年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)  加拿大_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_一年級_男   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_一年級_女   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_二年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_三年級_女   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   英國_高級中等學校_延修生_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_一年級_男   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_一年級_女   1
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_二年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_二年級_女   2
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_三年級_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_三年級_女   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_延修生_男   0
臺中市 臺中市高級中等學校外國學生數-學生數(單位:人)   越南_高級中等學校_延修生_女   0

總外國學生數: 32

按國家分組的學生數：
  國家  數值
 加拿大   0
  南韓   9
  印尼   1
  印度   1
  日本   4
  美國   4
  英國   3
 菲律賓   3
  越南   5
馬來西亞   2

按年級分組的學生數：
 年級  數值
一年級  14
三年級  10
二年級   8
延修生   0

按性別分組的學生數：
性別  數值
 女  13
 男  19
 pandas_tool
model:  ## 📊 臺中市高級中等學校外國學生數統計（2024 學年）

---

### 🧮 總體概覽

| 指標 | 數值 |
|------|------|
| **外國學生總數** | **32 人** |
| 男生 | 19 人 |
| 女生 | 13 人 |

---

### 🌍 按國家分組

| 國家 | 學生數 |
|------|:------:|
| 南韓 | 9 |
| 越南 | 5 |
| 美國 | 4 |
| 日本 | 4 |
| 英國 | 3 |
| 菲律賓 | 3 |
| 馬來西亞 | 2 |
| 印尼 | 1 |
| 印度 | 1 |
| 加拿大 | 0 |

> **南韓**學生最多（9人），其次為**越南**（5人），**美國**與**日本**並列第三（各4人）。

---

### 📚 按年級分組

| 年級 | 學生數 |
|------|:------:|
| 一年級 | 14 |
| 二年級 | 8 |
| 三年級 | 10 |
| 延修生 | 0 |

---

### 👤 按性別分組

| 性別 | 學生數 |
|------|:------:|
| 男 | 19 |
| 女 | 13 |

---

### 📋 完整明細資料（共 80 筆）

資料涵蓋 10 個國家 × 4 個年級（一～三年級 + 延修生）× 2 種性別（男/女）的交叉組合，共 80 筆記錄。以上為彙整後的統計結果，完整逐筆資料已於分析過程中列出。 []

跨文檔工作

In [18]:
from pathlib import Path

directory = "多檔案測試"

for file in os.listdir(directory):

    path = Path(file)
    
    if not file.endswith("json"):
        continue
    with open(os.path.join(directory, file), "r", encoding="utf-8") as f:
        data = json.load(f)
        df = pd.DataFrame(data=data)
        df.to_csv(os.path.join(directory, f"{path.stem}.csv"))

In [19]:
context = Context(directory=directory)

agent = create_agent(
    model=llm,
    name="analysis_agent_version_2",
    tools=tools,
    system_prompt=AGENT_INSTRUCTION_VERSION_2,
    middleware=[
        ToolRetryMiddleware(max_retries=2),
    ]
)

In [20]:
agent_input = {"messages": HumanMessage(content="台中市學生從2021年到2024年的變化")}

In [21]:
for update in agent.stream(
    agent_input,
    context=context,
    stream_mode="updates",
):
    # 只保留 model 和 tool 兩個 key
    for key, value in update.items():
        if key == "model":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].tool_calls)
        if key == "tools":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].name)

model:  我来帮您分析台中市学生从2021年到2024年的变化。首先，让我了解一下有哪些可用的数据文件。 [{'name': 'schema_tool', 'args': {'input': {}}, 'id': '3b9999ca-a7b1-4053-bec7-74adb8596a96', 'type': 'tool_call'}]
tools:  -多檔案測試\2021_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5294  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5569  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4531  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  4221  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   206  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


-多檔案測試\2022_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5245  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5375  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4489  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  4046  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   189  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


-多檔案測試\2023學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5325  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5277  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4283  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  3761  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   183  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


-多檔案測試\2024學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5246  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5538  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4010  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  3759  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   151  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


 schema_tool
model:  数据已经加载完毕，共有4个学年度（2021-2024）的档案。现在让我对这些数据进行全面分析。 [{'name': 'pandas_tool', 'args': {'input': {'files': ['2021_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2022_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2023學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2024學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv'], 'user_query': '台中市學生從2021年到2024年的變化。請分析：1. 各年度總畢業生人數變化 2. 各項目類別（項目欄位）有哪些 3. 各欄位名稱類別有哪些 4. 按項目分類各年度的數值變化 5. 升學vs就業的趨勢變化 6. 男女學生變化趨勢。請給出完整的統計摘要。'}}, 'id': '16ce2a12-7be0-454a-8909-ba42201be06c', 'type': 'tool_call'}]
tools:  ============================================================
臺中市高級中等學校應屆畢業生升學就業概況統計摘要 (2021-2024)
============================================================

1. 各年度總畢業生人數變化
年份
2021    25041
2022    24327
2023    23461
2024    23181

2. 各項目類別（唯一值）
  1. 高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)

3. 各欄位名稱類別（唯一值）
  1. 大學校院(大學)_普通科_男
  2. 大學校院(大學)_普通科_女
  3. 大學校院(大學)_專業群科(職業科)_男
  4. 大學校院(大學)_專業群科(職業科)_女
  5. 大學校院(大學)_綜合高中_男
  6. 大學校院(大學)_綜合高中_女
  7. 專科學校(二專)_專業群科(職業科)_女
  8. 大學校院(大學)_實用技能學程_男
  9. 大學校院(大學)_實用技能學程_女
  10. 大學校院(大學)_高級中等進修學校_男
  11. 大學校院(大學)_高級中等進修學校_女
  12. 專科學校(二專)_普通科_男
  13. 專科學校(二專)_普通科_女
  14. 專科學校(二專)_專業群科(職業科)_男
  15. 專科學校(二專)_綜合高中_男
  16. 專科學校(二專)_綜合高中_女
  17. 專科學校(二專)_實用技能學程_男
  18. 專科學校(二專)_實用技能學程_女
  19. 專科學校(二專)_高級中等進修學校_男
  20. 專科學校(二專)_高級中等進修學校_女
  21. 軍警學校_普通科_男
  22. 軍警學校_普通科_女
  23. 軍警學校_專業群科(職業科)_男
  24. 軍警學校_專業群科(職業科)_女
  25. 軍警學校_綜合高中_男
  26. 軍警學校_綜合高中_女
  27. 軍警學校_實用技能學程_男
  28. 軍警學校_實用技能學程_女
  29. 軍警學校_高級中等進修學校_男
  30. 軍警學校_高級中等進修學校_女
  31. 國外、大陸學校_普通科_男
  32. 國外、大陸學校_普通科_女
  33. 國外、大陸學校_專業群科(職業科)_男
  34. 國外、大陸學校_專業群科(職業科)_女
  35. 國外、大陸學校_綜合高中_男
  36. 國外、大陸學校_綜合高中_女
  37. 國外、大陸學校_實用技能學程_男
  38. 國外、大陸學校_實用技能學程_女
  39. 國外、大陸學校_高級中等進修學校_男
  40. 國外、大陸學校_高級中等進修學校_女
  41. 其他學校_普通科_男
  42. 其他學校_普通科_女
  43. 其他學校_專業群科(職業科)_男
  44. 其他學校_專業群科(職業科)_女
  45. 其他學校_綜合高中_男
  46. 其他學校_綜合高中_女
  47. 其他學校_實用技能學程_男
  48. 其他學校_實用技能學程_女
  49. 其他學校_高級中等進修學校_男
  50. 其他學校_高級中等進修學校_女
  51. 農林漁牧業_普通科_男
  52. 農林漁牧業_普通科_女
  53. 農林漁牧業_專業群科(職業科)_男
  54. 農林漁牧業_專業群科(職業科)_女
  55. 農林漁牧業_綜合高中_男
  56. 農林漁牧業_綜合高中_女
  57. 農林漁牧業_實用技能學程_男
  58. 農林漁牧業_實用技能學程_女
  59. 農林漁牧業_高級中等進修學校_男
  60. 農林漁牧業_高級中等進修學校_女
  61. 礦業及土石採取業_普通科_男
  62. 礦業及土石採取業_普通科_女
  63. 礦業及土石採取業_專業群科(職業科)_男
  64. 礦業及土石採取業_專業群科(職業科)_女
  65. 礦業及土石採取業_綜合高中_男
  66. 礦業及土石採取業_綜合高中_女
  67. 礦業及土石採取業_實用技能學程_男
  68. 礦業及土石採取業_實用技能學程_女
  69. 礦業及土石採取業_高級中等進修學校_男
  70. 礦業及土石採取業_高級中等進修學校_女
  71. 製造業_普通科_男
  72. 製造業_普通科_女
  73. 製造業_專業群科(職業科)_男
  74. 製造業_專業群科(職業科)_女
  75. 製造業_綜合高中_男
  76. 製造業_綜合高中_女
  77. 製造業_實用技能學程_男
  78. 製造業_實用技能學程_女
  79. 製造業_高級中等進修學校_男
  80. 製造業_高級中等進修學校_女
  81. 電力及燃氣供應業_普通科_男
  82. 電力及燃氣供應業_普通科_女
  83. 電力及燃氣供應業_專業群科(職業科)_男
  84. 電力及燃氣供應業_專業群科(職業科)_女
  85. 電力及燃氣供應業_綜合高中_男
  86. 電力及燃氣供應業_綜合高中_女
  87. 電力及燃氣供應業_實用技能學程_男
  88. 電力及燃氣供應業_實用技能學程_女
  89. 電力及燃氣供應業_高級中等進修學校_男
  90. 電力及燃氣供應業_高級中等進修學校_女
  91. 用水供應及污染整治業_普通科_男
  92. 用水供應及污染整治業_普通科_女
  93. 用水供應及污染整治業_專業群科(職業科)_男
  94. 用水供應及污染整治業_專業群科(職業科)_女
  95. 用水供應及污染整治業_綜合高中_男
  96. 用水供應及污染整治業_綜合高中_女
  97. 用水供應及污染整治業_實用技能學程_男
  98. 用水供應及污染整治業_實用技能學程_女
  99. 用水供應及污染整治業_高級中等進修學校_男
  100. 用水供應及污染整治業_高級中等進修學校_女
  101. 營造業_普通科_男
  102. 營造業_普通科_女
  103. 營造業_專業群科(職業科)_男
  104. 營造業_專業群科(職業科)_女
  105. 營造業_綜合高中_男
  106. 營造業_綜合高中_女
  107. 營造業_實用技能學程_男
  108. 營造業_實用技能學程_女
  109. 營造業_高級中等進修學校_男
  110. 營造業_高級中等進修學校_女
  111. 批發及零售業_普通科_男
  112. 批發及零售業_普通科_女
  113. 批發及零售業_專業群科(職業科)_男
  114. 批發及零售業_專業群科(職業科)_女
  115. 批發及零售業_綜合高中_男
  116. 批發及零售業_綜合高中_女
  117. 批發及零售業_實用技能學程_男
  118. 批發及零售業_實用技能學程_女
  119. 批發及零售業_高級中等進修學校_男
  120. 批發及零售業_高級中等進修學校_女
  121. 運輸倉儲業_普通科_男
  122. 運輸倉儲業_普通科_女
  123. 運輸倉儲業_專業群科(職業科)_男
  124. 運輸倉儲業_專業群科(職業科)_女
  125. 運輸倉儲業_綜合高中_男
  126. 運輸倉儲業_綜合高中_女
  127. 運輸倉儲業_實用技能學程_男
  128. 運輸倉儲業_實用技能學程_女
  129. 運輸倉儲業_高級中等進修學校_男
  130. 運輸倉儲業_高級中等進修學校_女
  131. 住宿及餐飲業_普通科_男
  132. 住宿及餐飲業_普通科_女
  133. 住宿及餐飲業_專業群科(職業科)_男
  134. 住宿及餐飲業_專業群科(職業科)_女
  135. 住宿及餐飲業_綜合高中_男
  136. 住宿及餐飲業_綜合高中_女
  137. 住宿及餐飲業_實用技能學程_男
  138. 住宿及餐飲業_實用技能學程_女
  139. 住宿及餐飲業_高級中等進修學校_男
  140. 住宿及餐飲業_高級中等進修學校_女
  141. 資訊及通訊傳播業_普通科_男
  142. 資訊及通訊傳播業_普通科_女
  143. 資訊及通訊傳播業_專業群科(職業科)_男
  144. 資訊及通訊傳播業_專業群科(職業科)_女
  145. 資訊及通訊傳播業_綜合高中_男
  146. 資訊及通訊傳播業_綜合高中_女
  147. 資訊及通訊傳播業_實用技能學程_男
  148. 資訊及通訊傳播業_實用技能學程_女
  149. 資訊及通訊傳播業_高級中等進修學校_男
  150. 資訊及通訊傳播業_高級中等進修學校_女
  151. 金融及保險業_普通科_男
  152. 金融及保險業_普通科_女
  153. 金融及保險業_專業群科(職業科)_男
  154. 金融及保險業_專業群科(職業科)_女
  155. 金融及保險業_綜合高中_男
  156. 金融及保險業_綜合高中_女
  157. 金融及保險業_實用技能學程_男
  158. 金融及保險業_實用技能學程_女
  159. 金融及保險業_高級中等進修學校_男
  160. 金融及保險業_高級中等進修學校_女
  161. 不動產業_普通科_男
  162. 不動產業_普通科_女
  163. 不動產業_專業群科(職業科)_男
  164. 不動產業_專業群科(職業科)_女
  165. 不動產業_綜合高中_男
  166. 不動產業_綜合高中_女
  167. 不動產業_實用技能學程_男
  168. 不動產業_實用技能學程_女
  169. 不動產業_高級中等進修學校_男
  170. 不動產業_高級中等進修學校_女
  171. 專業科學及技術服務業_普通科_男
  172. 專業科學及技術服務業_普通科_女
  173. 專業科學及技術服務業_專業群科(職業科)_男
  174. 專業科學及技術服務業_專業群科(職業科)_女
  175. 專業科學及技術服務業_綜合高中_男
  176. 專業科學及技術服務業_綜合高中_女
  177. 專業科學及技術服務業_實用技能學程_男
  178. 專業科學及技術服務業_實用技能學程_女
  179. 專業科學及技術服務業_高級中等進修學校_男
  180. 專業科學及技術服務業_高級中等進修學校_女
  181. 支援服務業_普通科_男
  182. 支援服務業_普通科_女
  183. 支援服務業_專業群科(職業科)_男
  184. 支援服務業_專業群科(職業科)_女
  185. 支援服務業_綜合高中_男
  186. 支援服務業_綜合高中_女
  187. 支援服務業_實用技能學程_男
  188. 支援服務業_實用技能學程_女
  189. 支援服務業_高級中等進修學校_男
  190. 支援服務業_高級中等進修學校_女
  191. 公共行政及國防；強制性社會安全_普通科_男
  192. 公共行政及國防；強制性社會安全_普通科_女
  193. 公共行政及國防；強制性社會安全_專業群科(職業科)_男
  194. 公共行政及國防；強制性社會安全_專業群科(職業科)_女
  195. 公共行政及國防；強制性社會安全_綜合高中_男
  196. 公共行政及國防；強制性社會安全_綜合高中_女
  197. 公共行政及國防；強制性社會安全_實用技能學程_男
  198. 公共行政及國防；強制性社會安全_實用技能學程_女
  199. 公共行政及國防；強制性社會安全_高級中等進修學校_男
  200. 公共行政及國防；強制性社會安全_高級中等進修學校_女
  201. 教育服務業_普通科_男
  202. 教育服務業_普通科_女
  203. 教育服務業_專業群科(職業科)_男
  204. 教育服務業_專業群科(職業科)_女
  205. 教育服務業_綜合高中_男
  206. 教育服務業_綜合高中_女
  207. 教育服務業_實用技能學程_男
  208. 教育服務業_實用技能學程_女
  209. 教育服務業_高級中等進修學校_男
  210. 教育服務業_高級中等進修學校_女
  211. 醫療保健及社會工作服務業_普通科_男
  212. 醫療保健及社會工作服務業_普通科_女
  213. 醫療保健及社會工作服務業_專業群科(職業科)_男
  214. 醫療保健及社會工作服務業_專業群科(職業科)_女
  215. 醫療保健及社會工作服務業_綜合高中_男
  216. 醫療保健及社會工作服務業_綜合高中_女
  217. 醫療保健及社會工作服務業_實用技能學程_男
  218. 醫療保健及社會工作服務業_實用技能學程_女
  219. 醫療保健及社會工作服務業_高級中等進修學校_男
  220. 醫療保健及社會工作服務業_高級中等進修學校_女
  221. 藝術娛樂及休閒服務業_普通科_男
  222. 藝術娛樂及休閒服務業_普通科_女
  223. 藝術娛樂及休閒服務業_專業群科(職業科)_男
  224. 藝術娛樂及休閒服務業_專業群科(職業科)_女
  225. 藝術娛樂及休閒服務業_綜合高中_男
  226. 藝術娛樂及休閒服務業_綜合高中_女
  227. 藝術娛樂及休閒服務業_實用技能學程_男
  228. 藝術娛樂及休閒服務業_實用技能學程_女
  229. 藝術娛樂及休閒服務業_高級中等進修學校_男
  230. 藝術娛樂及休閒服務業_高級中等進修學校_女
  231. 其他服務業_普通科_男
  232. 其他服務業_普通科_女
  233. 其他服務業_專業群科(職業科)_男
  234. 其他服務業_專業群科(職業科)_女
  235. 其他服務業_綜合高中_男
  236. 其他服務業_綜合高中_女
  237. 其他服務業_實用技能學程_男
  238. 其他服務業_實用技能學程_女
  239. 其他服務業_高級中等進修學校_男
  240. 其他服務業_高級中等進修學校_女
  241. 正在接受職業訓練_普通科_男
  242. 正在接受職業訓練_普通科_女
  243. 正在接受職業訓練_專業群科(職業科)_男
  244. 正在接受職業訓練_專業群科(職業科)_女
  245. 正在接受職業訓練_綜合高中_男
  246. 正在接受職業訓練_綜合高中_女
  247. 正在接受職業訓練_實用技能學程_男
  248. 正在接受職業訓練_實用技能學程_女
  249. 正在接受職業訓練_高級中等進修學校_男
  250. 正在接受職業訓練_高級中等進修學校_女
  251. 正在軍中服兵役(服兵役)_普通科_男
  252. 正在軍中服兵役(服兵役)_普通科_女
  253. 正在軍中服兵役(服兵役)_專業群科(職業科)_男
  254. 正在軍中服兵役(服兵役)_專業群科(職業科)_女
  255. 正在軍中服兵役(服兵役)_綜合高中_男
  256. 正在軍中服兵役(服兵役)_綜合高中_女
  257. 正在軍中服兵役(服兵役)_實用技能學程_男
  258. 正在軍中服兵役(服兵役)_實用技能學程_女
  259. 正在軍中服兵役(服兵役)_高級中等進修學校_男
  260. 正在軍中服兵役(服兵役)_高級中等進修學校_女
  261. 需要工作尚未找到_普通科_男
  262. 需要工作尚未找到_普通科_女
  263. 需要工作尚未找到_專業群科(職業科)_男
  264. 需要工作尚未找到_專業群科(職業科)_女
  265. 需要工作尚未找到_綜合高中_男
  266. 需要工作尚未找到_綜合高中_女
  267. 需要工作尚未找到_實用技能學程_男
  268. 需要工作尚未找到_實用技能學程_女
  269. 需要工作尚未找到_高級中等進修學校_男
  270. 需要工作尚未找到_高級中等進修學校_女
  271. 正在補習或自修準備升學_普通科_男
  272. 正在補習或自修準備升學_普通科_女
  273. 正在補習或自修準備升學_專業群科(職業科)_男
  274. 正在補習或自修準備升學_專業群科(職業科)_女
  275. 正在補習或自修準備升學_綜合高中_男
  276. 正在補習或自修準備升學_綜合高中_女
  277. 正在補習或自修準備升學_實用技能學程_男
  278. 正在補習或自修準備升學_實用技能學程_女
  279. 正在補習或自修準備升學_高級中等進修學校_男
  280. 正在補習或自修準備升學_高級中等進修學校_女
  281. 因健康不良在家休養_普通科_男
  282. 因健康不良在家休養_普通科_女
  283. 因健康不良在家休養_專業群科(職業科)_男
  284. 因健康不良在家休養_專業群科(職業科)_女
  285. 因健康不良在家休養_綜合高中_男
  286. 因健康不良在家休養_綜合高中_女
  287. 因健康不良在家休養_實用技能學程_男
  288. 因健康不良在家休養_實用技能學程_女
  289. 因健康不良在家休養_高級中等進修學校_男
  290. 因健康不良在家休養_高級中等進修學校_女
  291. 準備出國_普通科_男
  292. 準備出國_普通科_女
  293. 準備出國_專業群科(職業科)_男
  294. 準備出國_專業群科(職業科)_女
  295. 準備出國_綜合高中_男
  296. 準備出國_綜合高中_女
  297. 準備出國_實用技能學程_男
  298. 準備出國_實用技能學程_女
  299. 準備出國_高級中等進修學校_男
  300. 準備出國_高級中等進修學校_女
  301. 未升學未就業_其他_普通科_男
  302. 未升學未就業_其他_普通科_女
  303. 未升學未就業_其他_專業群科(職業科)_男
  304. 未升學未就業_其他_專業群科(職業科)_女
  305. 未升學未就業_其他_綜合高中_男
  306. 未升學未就業_其他_綜合高中_女
  307. 未升學未就業_其他_實用技能學程_男
  308. 未升學未就業_其他_實用技能學程_女
  309. 未升學未就業_其他_高級中等進修學校_男
  310. 未升學未就業_其他_高級中等進修學校_女
  311. 遷居國外_普通科_男
  312. 遷居國外_普通科_女
  313. 遷居國外_專業群科(職業科)_男
  314. 遷居國外_專業群科(職業科)_女
  315. 遷居國外_綜合高中_男
  316. 遷居國外_綜合高中_女
  317. 遷居國外_實用技能學程_男
  318. 遷居國外_實用技能學程_女
  319. 遷居國外_高級中等進修學校_男
  320. 遷居國外_高級中等進修學校_女
  321. 死亡_普通科_男
  322. 死亡_普通科_女
  323. 死亡_專業群科(職業科)_男
  324. 死亡_專業群科(職業科)_女
  325. 死亡_綜合高中_男
  326. 死亡_綜合高中_女
  327. 死亡_實用技能學程_男
  328. 死亡_實用技能學程_女
  329. 死亡_高級中等進修學校_男
  330. 死亡_高級中等進修學校_女
  331. 無法聯繫或不詳_普通科_男
  332. 無法聯繫或不詳_普通科_女
  333. 無法聯繫或不詳_專業群科(職業科)_男
  334. 無法聯繫或不詳_專業群科(職業科)_女
  335. 無法聯繫或不詳_綜合高中_男
  336. 無法聯繫或不詳_綜合高中_女
  337. 無法聯繫或不詳_實用技能學程_男
  338. 無法聯繫或不詳_實用技能學程_女
  339. 無法聯繫或不詳_高級中等進修學校_男
  340. 無法聯繫或不詳_高級中等進修學校_女
  341. 大學校院(大學)_進修部(學校)_男
  342. 大學校院(大學)_進修部(學校)_女
  343. 專科學校(二專)_進修部(學校)_男
  344. 專科學校(二專)_進修部(學校)_女
  345. 軍警學校_進修部(學校)_男
  346. 軍警學校_進修部(學校)_女
  347. 國外、大陸學校_進修部(學校)_男
  348. 國外、大陸學校_進修部(學校)_女
  349. 其他學校_進修部(學校)_男
  350. 其他學校_進修部(學校)_女
  351. 農林漁牧業_進修部(學校)_男
  352. 農林漁牧業_進修部(學校)_女
  353. 礦業及土石採取業_進修部(學校)_男
  354. 礦業及土石採取業_進修部(學校)_女
  355. 製造業_進修部(學校)_男
  356. 製造業_進修部(學校)_女
  357. 電力及燃氣供應業_進修部(學校)_男
  358. 電力及燃氣供應業_進修部(學校)_女
  359. 用水供應及污染整治業_進修部(學校)_男
  360. 用水供應及污染整治業_進修部(學校)_女
  361. 營造業_進修部(學校)_男
  362. 營造業_進修部(學校)_女
  363. 批發及零售業_進修部(學校)_男
  364. 批發及零售業_進修部(學校)_女
  365. 運輸倉儲業_進修部(學校)_男
  366. 運輸倉儲業_進修部(學校)_女
  367. 住宿及餐飲業_進修部(學校)_男
  368. 住宿及餐飲業_進修部(學校)_女
  369. 資訊及通訊傳播業_進修部(學校)_男
  370. 資訊及通訊傳播業_進修部(學校)_女
  371. 金融及保險業_進修部(學校)_男
  372. 金融及保險業_進修部(學校)_女
  373. 不動產業_進修部(學校)_男
  374. 不動產業_進修部(學校)_女
  375. 專業科學及技術服務業_進修部(學校)_男
  376. 專業科學及技術服務業_進修部(學校)_女
  377. 支援服務業_進修部(學校)_男
  378. 支援服務業_進修部(學校)_女
  379. 公共行政及國防；強制性社會安全_進修部(學校)_男
  380. 公共行政及國防；強制性社會安全_進修部(學校)_女
  381. 教育服務業_進修部(學校)_男
  382. 教育服務業_進修部(學校)_女
  383. 醫療保健及社會工作服務業_進修部(學校)_男
  384. 醫療保健及社會工作服務業_進修部(學校)_女
  385. 藝術娛樂及休閒服務業_進修部(學校)_男
  386. 藝術娛樂及休閒服務業_進修部(學校)_女
  387. 其他服務業_進修部(學校)_男
  388. 其他服務業_進修部(學校)_女
  389. 正在接受職業訓練_進修部(學校)_男
  390. 正在接受職業訓練_進修部(學校)_女
  391. 正在軍中服兵役(服兵役)_進修部(學校)_男
  392. 正在軍中服兵役(服兵役)_進修部(學校)_女
  393. 需要工作尚未找到_進修部(學校)_男
  394. 需要工作尚未找到_進修部(學校)_女
  395. 正在補習或自修準備升學_進修部(學校)_男
  396. 正在補習或自修準備升學_進修部(學校)_女
  397. 因健康不良在家休養_進修部(學校)_男
  398. 因健康不良在家休養_進修部(學校)_女
  399. 準備出國_進修部(學校)_男
  400. 準備出國_進修部(學校)_女
  401. 未升學未就業_其他_進修部(學校)_男
  402. 未升學未就業_其他_進修部(學校)_女
  403. 遷居國外_進修部(學校)_男
  404. 遷居國外_進修部(學校)_女
  405. 死亡_進修部(學校)_男
  406. 死亡_進修部(學校)_女
  407. 無法聯繫或不詳_進修部(學校)_男
  408. 無法聯繫或不詳_進修部(學校)_女

4. 按項目分類各年度的數值變化
年份                            2021   2022   2023   2024
項目
高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  25041  24327  23461  23181

5. 升學vs就業的趨勢變化
路徑分類    其他     升學
年份
2021  3701  21340
2022  3353  20974
2023  2934  20527
2024  2641  20540

6. 男女學生變化趨勢
性別        女      男
年份
2021  12100  12941
2022  11662  12665
2023  11125  12336
2024  11352  11829

============================================================
分析完成
 pandas_tool
model:  现在让我进一步获取更详细的分析，包括升学类别的细分和男女在各升学管道的分布变化。 [{'name': 'pandas_tool', 'args': {'input': {'files': ['2021_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2022_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2023學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2024學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv'], 'user_query': '請做以下分析：1. 將欄位名稱拆分成「去向類別」、「科別」、「性別」三個維度（例如：大學校院(大學)_普通科_男 → 去向=大學校院(大學), 科別=普通科, 性別=男）。2. 按去向類別（大學校院、專科學校、軍警學校、國外大陸學校、其他學校、各行業就業、未就業等）匯總各年度數據。3. 按科別（普通科、專業群科職業科、綜合高中、實用技能學程、高級中等進修學校、進修部學校）匯總各年度數據。4. 計算各年度年增減率。5. 找出變化最大的前10個欄位名稱。'}}, 'id': '53fe63cf-0b2a-434b-89d5-6bb3e90479cc', 'type': 'tool_call'}]

<string>:41: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.

tools:  ===== 按去向類別匯總各年度數據 =====
  年份              去向    數值
2021            不動產業     8
2021          住宿及餐飲業   719
2021 公共行政及國防；強制性社會安全   157
2021            其他學校    10
2021           其他服務業   214
2021       因健康不良在家休養    24
2021         國外、大陸學校   256
2021        大學校院(大學) 21025
2021      專業科學及技術服務業   141
2021        專科學校(二專)   175
2021          批發及零售業   213
2021           支援服務業   118
2021           教育服務業    10
2021          未升學未就業    42
2021        正在接受職業訓練    61
2021     正在補習或自修準備升學   273
2021    正在軍中服兵役(服兵役)   173
2021              死亡     0
2021            準備出國    18
2021         無法聯繫或不詳   103
2021             營造業   104
2021      用水供應及污染整治業     8
2021        礦業及土石採取業    10
2021      藝術娛樂及休閒服務業   130
2021             製造業   429
2021        資訊及通訊傳播業     9
2021            軍警學校   205
2021           農林漁牧業    36
2021           運輸倉儲業    84
2021            遷居國外     0
2021    醫療保健及社會工作服務業    23
2021          金融及保險業     5
2021        電力及燃氣供應業    37
2021        需要工作尚未找到   221
2022            不動產業     7
2022          住宿及餐飲業   672
2022 公共行政及國防；強制性社會安全   113
2022            其他學校    14
2022           其他服務業   303
2022       因健康不良在家休養    14
2022         國外、大陸學校   281
2022        大學校院(大學) 20672
2022      專業科學及技術服務業   150
2022        專科學校(二專)    97
2022          批發及零售業   159
2022           支援服務業   112
2022           教育服務業     5
2022          未升學未就業    33
2022        正在接受職業訓練    41
2022     正在補習或自修準備升學   269
2022    正在軍中服兵役(服兵役)   155
2022              死亡     1
2022            準備出國    27
2022         無法聯繫或不詳    61
2022             營造業   122
2022      用水供應及污染整治業     3
2022        礦業及土石採取業     7
2022      藝術娛樂及休閒服務業   121
2022             製造業   234
2022        資訊及通訊傳播業    31
2022            軍警學校   237
2022           農林漁牧業    26
2022           運輸倉儲業    74
2022            遷居國外     5
2022    醫療保健及社會工作服務業    20
2022          金融及保險業    11
2022        電力及燃氣供應業    45
2022        需要工作尚未找到   205
2023            不動產業    14
2023          住宿及餐飲業   539
2023 公共行政及國防；強制性社會安全   107
2023            其他學校    15
2023           其他服務業   123
2023       因健康不良在家休養    14
2023         國外、大陸學校   236
2023        大學校院(大學) 20109
2023      專業科學及技術服務業   157
2023        專科學校(二專)    43
2023          批發及零售業   193
2023           支援服務業    88
2023           教育服務業     9
2023          未升學未就業    31
2023        正在接受職業訓練    39
2023     正在補習或自修準備升學   387
2023    正在軍中服兵役(服兵役)   192
2023              死亡     1
2023            準備出國    58
2023         無法聯繫或不詳    57
2023             營造業   134
2023      用水供應及污染整治業     3
2023        礦業及土石採取業    12
2023      藝術娛樂及休閒服務業   100
2023             製造業   191
2023        資訊及通訊傳播業     7
2023            軍警學校   223
2023           農林漁牧業    25
2023           運輸倉儲業    74
2023            遷居國外     7
2023    醫療保健及社會工作服務業    26
2023          金融及保險業    15
2023        電力及燃氣供應業    24
2023        需要工作尚未找到   208
2024            不動產業     4
2024          住宿及餐飲業   461
2024 公共行政及國防；強制性社會安全   104
2024            其他學校    31
2024           其他服務業   179
2024       因健康不良在家休養    13
2024         國外、大陸學校   206
2024        大學校院(大學) 20098
2024      專業科學及技術服務業   127
2024        專科學校(二專)    51
2024          批發及零售業   137
2024           支援服務業   121
2024           教育服務業    10
2024          未升學未就業    26
2024        正在接受職業訓練    49
2024     正在補習或自修準備升學   416
2024    正在軍中服兵役(服兵役)   251
2024              死亡     1
2024            準備出國    56
2024         無法聯繫或不詳    21
2024             營造業    83
2024      用水供應及污染整治業     4
2024        礦業及土石採取業    11
2024      藝術娛樂及休閒服務業    65
2024             製造業   153
2024        資訊及通訊傳播業     7
2024            軍警學校   235
2024           農林漁牧業    22
2024           運輸倉儲業    24
2024            遷居國外     6
2024    醫療保健及社會工作服務業    11
2024          金融及保險業    10
2024        電力及燃氣供應業    23
2024        需要工作尚未找到   165

===== 按去向類別各年度年增減率 (%) =====
去向          不動產業     住宿及餐飲業  公共行政及國防；強制性社會安全        其他學校      其他服務業  因健康不良在家休養    國外、大陸學校  大學校院(大學)  專業科學及技術服務業   專科學校(二專)     批發及零售業      支援服務業      教育服務業     未升學未就業   正在接受職業訓練  正在補習或自修準備升學  正在軍中服兵役(服兵役)   死亡        準備出國    無法聯繫或不詳        營造業  用水供應及污染整治業   礦業及土石採取業  藝術娛樂及休閒服務業        製造業    資訊及通訊傳播業       軍警學校      農林漁牧業      運輸倉儲業       遷居國外  醫療保健及社會工作服務業      金融及保險業   電力及燃氣供應業   需要工作尚未找到
年份
2021         NaN        NaN              NaN         NaN        NaN        NaN        NaN       NaN         NaN        NaN        NaN        NaN        NaN        NaN        NaN          NaN           NaN  NaN         NaN        NaN        NaN         NaN        NaN         NaN        NaN         NaN        NaN        NaN        NaN        NaN           NaN         NaN        NaN        NaN
2022  -12.500000  -6.536857       -28.025478   40.000000  41.588785 -41.666667   9.765625 -1.678954    6.382979 -44.571429 -25.352113  -5.084746 -50.000000 -21.428571 -32.786885    -1.465201    -10.404624  inf   50.000000 -40.776699  17.307692  -62.500000 -30.000000   -6.923077 -45.454545  244.444444  15.609756 -27.777778 -11.904762        inf    -13.043478  120.000000  21.621622  -7.239819
2023  100.000000 -19.791667        -5.309735    7.142857 -59.405941   0.000000 -16.014235 -2.723491    4.666667 -55.670103  21.383648 -21.428571  80.000000  -6.060606  -4.878049    43.866171     23.870968  0.0  114.814815  -6.557377   9.836066    0.000000  71.428571  -17.355372 -18.376068  -77.419355  -5.907173  -3.846154   0.000000  40.000000     30.000000   36.363636 -46.666667   1.463415
2024  -71.428571 -14.471243        -2.803738  106.666667  45.528455  -7.142857 -12.711864 -0.054702  -19.108280  18.604651 -29.015544  37.500000  11.111111 -16.129032  25.641026     7.493540     30.729167  0.0   -3.448276 -63.157895 -38.059701   33.333333  -8.333333  -35.000000 -19.895288    0.000000   5.381166 -12.000000 -67.567568 -14.285714    -57.692308  -33.333333  -4.166667 -20.673077

===== 按科別匯總各年度數據 =====
  年份        科别    數值
2021        其他    42
2021    實用技能學程  1323
2021 專業群科(職業科) 10374
2021       普通科 11586
2021      綜合高中   457
2021  高級中等進修學校  1259
2022        其他    33
2022    實用技能學程  1482
2022 專業群科(職業科)  9802
2022       普通科 11394
2022      綜合高中   478
2022   進修部(學校)  1138
2023        其他    31
2023    實用技能學程  1409
2023 專業群科(職業科)  9209
2023       普通科 11440
2023      綜合高中   409
2023   進修部(學校)   963
2024        其他    26
2024    實用技能學程  1391
2024 專業群科(職業科)  8844
2024       普通科 11584
2024      綜合高中   396
2024   進修部(學校)   940

===== 按科別各年度年增減率 (%) =====
科别           其他     實用技能學程  專業群科(職業科)       普通科       綜合高中    進修部(學校)  高級中等進修學校
年份
2021        NaN        NaN        NaN       NaN        NaN        NaN       NaN
2022 -21.428571  12.018141  -5.513784 -1.657172   4.595186        NaN       0.0
2023  -6.060606  -4.925776  -6.049786  0.403721 -14.435146 -15.377856       0.0
2024 -16.129032  -1.277502  -3.963514  1.258741  -3.178484  -2.388370       0.0

===== 變化最大的前10個欄位名稱 (以標準差衡量) =====
欄位名稱
大學校院(大學)_專業群科(職業科)_男        238.242698
大學校院(大學)_專業群科(職業科)_女        227.168623
大學校院(大學)_普通科_女              137.887333
大學校院(大學)_實用技能學程_男            59.779456
正在補習或自修準備升學_普通科_男            48.583262
大學校院(大學)_實用技能學程_女            47.724906
製造業_專業群科(職業科)_男              46.224092
大學校院(大學)_普通科_男               39.059783
正在軍中服兵役(服兵役)_專業群科(職業科)_男     34.412934
專科學校(二專)_專業群科(職業科)_女         31.805398
 pandas_tool
model:  ## 📊 臺中市高級中等學校應屆畢業生升學就業概況：2021-2024 年變化分析

---

### 一、📉 總畢業生人數：連續四年下滑

| 年度 | 總畢業生人數 | 年增減率 |
|------|:----------:|:--------:|
| 2021 | **25,041** | — |
| 2022 | 24,327 | **-2.85%** |
| 2023 | 23,461 | **-3.56%** |
| 2024 | 23,181 | **-1.19%** |

> 🔴 四年累計減少 **1,860 人（-7.43%）**，反映少子化趨勢持續衝擊臺中市高中職畢業生規模。

---

### 二、🎓 升學 vs 就業/其他：升學仍是主流，但「重考補習」顯著增加

| 年度 | 升學人數 | 佔比 | 就業/其他 | 佔比 |
|------|:------:|:---:|:-------:|:---:|
| 2021 | 21,340 | 85.2% | 3,701 | 14.8% |
| 2022 | 20,974 | 86.2% | 3,353 | 13.8% |
| 2023 | 20,527 | 87.5% | 2,934 | 12.5% |
| 2024 | 20,540 | 88.6% | 2,641 | 11.4% |

**關鍵趨勢：**
- 升學人數雖略降但佔比持續攀升（85.2% → 88.6%），顯示就業意願持續降低。
- 🔺 **「正在補習或自修準備升學」** 從 273 人暴增至 **416 人（+52.4%）**，反映重考風氣升溫。
- 🔺 **「正在軍中服兵役」** 從 173 人增至 **251 人（+45.1%）**。

---

### 三、👫 男女學生變化：男生降幅大於女生

| 年度 | 男生 | 女生 | 男女比 |
|------|:---:|:---:|:-----:|
| 2021 | 12,941 | 12,100 | 51.7 : 48.3 |
| 2022 | 12,665 | 11,662 | 52.1 : 47.9 |
| 2023 | 12,336 | 11,125 | 52.6 : 47.4 |
| 2024 | 11,829 | 11,352 | 51.0 : 49.0 |

> 男生四年減少 **1,112 人（-8.6%）**，女生減少 **748 人（-6.2%）**。2024 年女生人數出現回升（+227人），男女差距縮小。

---

### 四、🏫 按升學去向分析

**大學校院（大學）** 始終是最大去向，但逐年微幅下滑：

| 年度 | 大學校院(大學) | 軍警學校 | 國外/大陸 | 專科學校(二專) |
|------|:----------:|:------:|:--------:|:----------:|
| 2021 | 21,025 | 205 | 256 | 175 |
| 2022 | 20,672 | 237 | 281 | 97 |
| 2023 | 20,109 | 223 | 236 | 43 |
| 2024 | 20,098 | 235 | 206 | 51 |

> 大學校院四年減少 **927 人（-4.4%）**，專科學校（二專）大幅萎縮 **-70.9%**。

---

### 五、💼 就業行業 Top 5 變化

| 行業 | 2021 | 2024 | 變化 |
|------|:---:|:---:|:---:|
| 🏭 製造業 | 429 | 153 | **-64.3%** |
| 🍽️ 住宿及餐飲業 | 719 | 461 | **-35.9%** |
| 🛒 批發及零售業 | 213 | 137 | **-35.7%** |
| 🏛️ 公共行政及國防 | 157 | 104 | **-33.8%** |
| 🎨 藝術娛樂及休閒服務業 | 130 | 65 | **-50.0%** |

> 幾乎所有就業行業人數都大幅下降，反映畢業生直接進入職場的意願持續走低。

---

### 六、📚 按科別分析：職業科萎縮最嚴重

| 科別 | 2021 | 2024 | 四年變化 |
|------|:---:|:---:|:------:|
| 普通科 | 11,586 | 11,584 | **-0.02%（持平）** |
| 專業群科（職業科） | 10,374 | 8,844 | **-14.7% 🔴** |
| 實用技能學程 | 1,323 | 1,391 | +5.1% |
| 綜合高中 | 457 | 396 | **-13.3%** |
| 進修部/進修學校 | 1,259 | 940 | **-25.3%** |

> 🔴 **專業群科（職業科）四年大減 1,530 人**，是總人數下滑的主因。普通科則幾乎持平，顯示學術導向依然穩固。

---

### 七、🔝 變化最大的前 5 個細項（標準差最大）

| 排名 | 欄位名稱 | 變化特徵 |
|:--:|------|------|
| 1 | 大學校院(大學)_專業群科(職業科)_男 | 4,531→4,489→4,283→4,010（**-521人**） |
| 2 | 大學校院(大學)_專業群科(職業科)_女 | 4,221→4,046→3,761→3,759（**-462人**） |
| 3 | 大學校院(大學)_普通科_女 | 5,569→5,375→5,277→5,538（波動大） |
| 4 | 大學校院(大學)_實用技能學程_男 | 持續增長 |
| 5 | 正在補習或自修準備升學_普通科_男 | 顯著增加 |

---

### 📌 總結

| 指標 | 趨勢 | 關鍵數字 |
|------|:--:|------|
| 總畢業生 | 🔻 持續下降 | -7.43%（四年） |
| 升學比例 | 🔺 持續上升 | 85.2% → 88.6% |
| 職業科學生 | 🔻 大幅萎縮 | -14.7% |
| 普通科學生 | ➡️ 基本持平 | -0.02% |
| 重考補習 | 🔺 顯著增加 | +52.4% |
| 直接就業 | 🔻 大幅減少 | 各行業普降 30-60% |

> 臺中市高中職畢業生正面臨 **少子化 + 升學導向強化 + 職業科萎縮** 的三重結構性變化，對技職教育體系帶來深遠影響。 []

## 報告生成

In [22]:
from textwrap import dedent
from pydantic import BaseModel, Field
from langchain.tools import BaseTool, ToolRuntime
from langchain_core.output_parsers import PydanticOutputParser, StrOutputParser
from langchain_core.runnables import Runnable

REPORT_SYSTEM_PROMPT = dedent("""
# Role
你是一位專業的報告撰寫專家，擅長將數據分析結果轉化為結構清晰、易讀的書面報告。

# Goal
根據使用者需求與分析結果，生成一份完整的文字報告。報告應包含：標題、摘要、數據分析結果、結論與建議。

# Input
- <requirement>: 使用者的原始需求描述
- <analysis_result>: 數據分析工具回傳的結果

# Rule
- 報告必須使用繁體中文撰寫
- 報告結構：標題 → 摘要 → 分析內容 → 結論
- 保留分析結果中的所有關鍵數字與統計數據
- 使用清晰的段落分隔，便於後續 Word 排版
- 以純文字輸出，不使用 markdown 語法

# Constraints
- 不得虛構或竄改分析結果中的數據
- 不得添加未經分析驗證的推測
""")


class ReportInputs(BaseModel):
    requirement: str = Field(
        description="The user's original requirement or question that triggered the analysis.")
    analysis_result: str = Field(
        description="The raw output from data analysis tools (e.g., pandas_tool results) to be turned into a report.")


class ReportTool(BaseTool):
    name: str = "report_tool"

    description_template: str = dedent("""
    Generates a structured text report based on user requirements and data analysis results.
    Use this tool when you need to produce a formal written report from analysis output.

    {input_format_instructions}
    """)

    input_parser: PydanticOutputParser = PydanticOutputParser(pydantic_object=ReportInputs)
    input_format_instructions: str = input_parser.get_format_instructions()
    description: str = description_template.format(input_format_instructions=input_format_instructions)

    pipeline: Runnable

    @classmethod
    def create(cls, llm: Runnable):
        input_ = {
            "system": {"template": REPORT_SYSTEM_PROMPT},
            "human": {
                "template": dedent("""
                    <requirement>: {requirement}
                    <analysis_result>: {analysis_result}
                """),
                "input_variables": ["requirement", "analysis_result"]
            }
        }
        pipeline = build_standard_chat_prompt_template(input_) | llm | StrOutputParser()
        return cls(pipeline=pipeline)

    def _run(self, runtime: ToolRuntime, **input):
        args = input.get("input", input)
        requirement = args["requirement"]
        analysis_result = args["analysis_result"]

        report = self.pipeline.invoke({
            "requirement": requirement,
            "analysis_result": analysis_result
        })

        return report

    async def _arun(self, runtime: ToolRuntime):
        return "Not implemented yet"

In [23]:
import io
import os
from contextlib import redirect_stdout
from pydantic import BaseModel, Field

WORD_FORMAT_SYSTEM_PROMPT = dedent("""
# Role
你是一位專業的 Python 文檔自動化專家，擅長使用 python-docx 庫將文字報告排版為精美的 Word 文件。

# Goal
根據輸入的報告文字，生成一段完整的 Python 代碼，使用 python-docx 創建格式化的 Word 文件並儲存。

# Input
- <report>: 需要排版的報告文字內容
- <output_path>: Word 文件的輸出路徑

# Rule
- 使用 `from docx import Document` 創建文件
- 使用 `docx.shared.Pt` 設定字型大小
- 使用 `docx.shared.RGBColor` 設定顏色
- 使用 `docx.enum.text.WD_ALIGN_PARAGRAPH` 設定對齊
- 標題使用 18pt 粗體置中
- 章節標題使用 14pt 粗體
- 內文使用 12pt 正常字體
- 設定頁面邊距為 2.54cm（標準 A4）
- 最後使用 `doc.save(output_path)` 儲存
- 使用 `print()` 輸出成功訊息

# Constraints
- 只輸出 Python 代碼，不要包含 markdown 標記
- 代碼必須完整可執行，包含所有必要的 import
- 不要使用未安裝的第三方庫

# Reasoning (Chain of Thought)
Step 1: 解析報告結構，識別標題、章節、段落
Step 2: 規劃 Word 排版格式（字型、大小、對齊）
Step 3: 生成完整的 python-docx 代碼
Step 4: 確認代碼包含 save 操作
""")


class WordFormatInputs(BaseModel):
    report: str = Field(
        description="The full text report content to be formatted into a Word document.")
    output_path: str = Field(
        default="report_output.docx",
        description="File path where the generated .docx file will be saved.")


class WordFormatTool(BaseTool):
    name: str = "word_format_tool"

    description_template: str = dedent("""
    Formats a text report into a Word (.docx) document using python-docx.
    Generates and executes Python code to create a professionally formatted Word file.
    Use this tool when you need to convert a plain text report into a styled Word document.

    {input_format_instructions}
    """)

    input_parser: PydanticOutputParser = PydanticOutputParser(pydantic_object=WordFormatInputs)
    input_format_instructions: str = input_parser.get_format_instructions()
    description: str = description_template.format(input_format_instructions=input_format_instructions)

    pipeline: Runnable

    @classmethod
    def create(cls, llm: Runnable):
        input_ = {
            "system": {"template": WORD_FORMAT_SYSTEM_PROMPT},
            "human": {
                "template": dedent("""
                    <report>: {report}
                    <output_path>: {output_path}
                """),
                "input_variables": ["report", "output_path"]
            }
        }
        pipeline = build_standard_chat_prompt_template(input_) | llm | StrOutputParser()
        return cls(pipeline=pipeline)

    def _run(self, runtime: ToolRuntime, **input):

        args = input.get("input", input)
        report = args["report"]
        output_path = args.get("output_path", "report_output.docx")

        code = self.pipeline.invoke({
            "report": report,
            "output_path": output_path
        })

        stdout_capture = io.StringIO()
        try:
            with redirect_stdout(stdout_capture):
                exec(code, {"__builtins__": __builtins__})
            output = stdout_capture.getvalue()
            if not output:
                output = f"Word document saved to: {output_path}"
        except Exception as e:
            output = f"WORD FORMAT ERROR: {str(e)}"

        return output

    async def _arun(self, runtime: ToolRuntime):
        return "Not implemented yet"

In [24]:
from pydantic import BaseModel, Field

CODE_FIX_SYSTEM_PROMPT = dedent("""
# Role
你是一位專業的 Python 代碼調試專家，擅長快速定位並修復 python-docx 排版代碼中的錯誤。

# Goal
根據錯誤訊息與失敗的代碼，生成修正後的完整 Python 代碼。

# Input
- <error_message>: 執行失敗的錯誤訊息
- <failed_code>: 導致錯誤的原始代碼
- <report>: 原始報告文字（供參考）
- <output_path>: Word 輸出路徑

# Rule
- 仔細分析錯誤訊息，定位根本原因
- 修正代碼中的語法錯誤、API 使用錯誤或邏輯問題
- 保持原有的排版意圖與格式設定
- 輸出完整的可執行代碼，而非僅修正片段
- 常見問題檢查：import 缺失、API 名稱錯誤、參數型別錯誤、NoneType 存取

# Constraints
- 只輸出 Python 代碼，不要包含 markdown 標記
- 代碼必須完整可執行
- 不要引入新的第三方庫

# Reasoning (Chain of Thought)
Step 1: 閱讀錯誤訊息，定位錯誤類型和位置
Step 2: 檢查對應的代碼行，找出根本原因
Step 3: 修正錯誤，確保代碼邏輯正確
Step 4: 輸出完整的修正代碼
""")


class CodeFixInputs(BaseModel):
    error_message: str = Field(
        description="The full error message or traceback from the failed code execution.")
    failed_code: str = Field(
        description="The complete Python code that produced the error.")
    report: str = Field(
        default="",
        description="The original report text that was being formatted, for context.")
    output_path: str = Field(
        default="report_output.docx",
        description="The target output path for the Word document.")


class CodeFixTool(BaseTool):
    name: str = "code_fix_tool"

    description_template: str = dedent("""
    Fixes Python code that failed during Word document generation.
    Analyzes the error message and failed code, then produces corrected code.
    Use this tool when WordFormatTool returns an error and the code needs debugging.

    {input_format_instructions}
    """)

    input_parser: PydanticOutputParser = PydanticOutputParser(pydantic_object=CodeFixInputs)
    input_format_instructions: str = input_parser.get_format_instructions()
    description: str = description_template.format(input_format_instructions=input_format_instructions)

    pipeline: Runnable

    @classmethod
    def create(cls, llm: Runnable):
        input_ = {
            "system": {"template": CODE_FIX_SYSTEM_PROMPT},
            "human": {
                "template": dedent("""
                    <error_message>: {error_message}
                    <failed_code>: {failed_code}
                    <report>: {report}
                    <output_path>: {output_path}
                """),
                "input_variables": ["error_message", "failed_code", "report", "output_path"]
            }
        }
        pipeline = build_standard_chat_prompt_template(input_) | llm | StrOutputParser()
        return cls(pipeline=pipeline)

    def _run(self, runtime: ToolRuntime, **input):

        args = input.get("input", input)
        error_message = args["error_message"]
        failed_code = args["failed_code"]
        report = args.get("report", "")
        output_path = args.get("output_path", "report_output.docx")

        fixed_code = self.pipeline.invoke({
            "error_message": error_message,
            "failed_code": failed_code,
            "report": report,
            "output_path": output_path
        })

        return fixed_code

    async def _arun(self, runtime: ToolRuntime):
        return "Not implemented yet"

In [25]:
from langchain.agents.middleware.model_call_limit import ModelCallLimitMiddleware


FULL_AGENT_INSTRUCTION = dedent("""
# Role
你是一位專業的數據分析與報告自動化顧問。你的工作流程是：分析數據 → 生成報告 → 排版 Word → 修正錯誤。

# Goal
根據使用者需求，完成從數據分析到 Word 報告輸出的完整流程。

# Tool
你可以使用以下工具：
- **schema_tool**: 讀取 CSV 檔案結構
- **pandas_tool**: 執行數據分析（需傳入 context=schema_tool 輸出、user_query=使用者原始問題）
- **report_tool**: 根據分析結果生成文字報告（需傳入 requirement=使用者需求、analysis_result=pandas_tool 輸出）
- **word_format_tool**: 將報告排版為 Word 文件（需傳入 report=report_tool 輸出）
- **code_fix_tool**: 修復 Word 排版代碼錯誤（需傳入 error_message、failed_code、report）

# Rule
1. 先使用 schema_tool 了解資料結構
2. 使用 pandas_tool 進行數據分析：將 schema_tool 的完整輸出作為 `context` 參數，使用者的原始問題作為 `user_query` 參數傳入
3. 使用 report_tool 生成文字報告：將使用者需求作為 `requirement`，pandas_tool 的輸出作為 `analysis_result` 傳入
4. 使用 word_format_tool 將報告轉為 Word 文件：將 report_tool 的輸出作為 `report` 參數傳入
5. 若 word_format_tool 返回錯誤（含 "WORD FORMAT ERROR"），使用 code_fix_tool 修正代碼後重試

# Constraints
- 必須按順序執行，不可跳過步驟
- 每個工具所需的參數必須正確傳入，不可遺漏
- 若工具返回錯誤，如實告知使用者
""")


all_tools = [
    SchemaTool.create(llm=llm),
    PandasTool.create(llm=llm),
    ReportTool.create(llm=llm),
    WordFormatTool.create(llm=llm),
    CodeFixTool.create(llm=llm),
]

full_agent = create_agent(
    model=llm,
    name="full_report_agent",
    tools=all_tools,
    system_prompt=FULL_AGENT_INSTRUCTION,
    middleware=[
        ToolRetryMiddleware(max_retries=2),
        ModelCallLimitMiddleware(run_limit=30, exit_behavior="end"),
    ]
)

print("Full report agent created with all 5 tools.")

Full report agent created with all 5 tools.

In [26]:
# 使用範例：從數據分析到 Word 報告
context = Context(directory="./多檔案測試")

agent_input = {
    "messages": HumanMessage(content="分析台中市學生數量從2021年到2024年的變化，並生成 Word 報告")
}

# agent_result = full_agent.invoke(agent_input, context=context)

# print("\\n" + "=" * 50)
# print("Final Result:")
# print(agent_result["messages"][-1].content)

In [27]:
for update in full_agent.stream(
    agent_input,
    context=context,
    stream_mode="updates",
):
    # 只保留 model 和 tool 兩個 key
    for key, value in update.items():
        if key == "model":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].tool_calls)
        if key == "tools":
            print(f"{key}: ", value["messages"][0].content, value['messages'][0].name)

model:  好的！我將按照流程逐步完成。首先，讓我了解數據的結構。 [{'name': 'schema_tool', 'args': {'input': {}}, 'id': '2dd5b78a-7e9b-4dab-819a-7d737a61cb5a', 'type': 'tool_call'}]
tools:  -./多檔案測試\2021_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5294  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5569  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4531  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  4221  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   206  2021-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


-./多檔案測試\2022_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5245  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5375  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4489  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  4046  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   189  2022-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


-./多檔案測試\2023學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5325  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5277  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4283  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  3761  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   183  2023-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


-./多檔案測試\2024學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv: <class 'pandas.core.frame.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  340 non-null    int64
 1   地區          340 non-null    object
 2   項目          340 non-null    object
 3   欄位名稱        340 non-null    object
 4   數值          340 non-null    int64
 5   資料時間日期      340 non-null    object
 6   資料週期        340 non-null    object
 7   郵遞區號        340 non-null    int64
 8   機關代碼        340 non-null    object
 9   電子郵件        340 non-null    object
 10  行動電話        340 non-null    int64
 11  市話          340 non-null    object
 12  縣市別代碼       340 non-null    int64
 13  行政區域代碼      340 non-null    int64
dtypes: int64(6), object(8)
memory usage: 37.3+ KB
   Unnamed: 0   地區                           項目                  欄位名稱    數值               資料時間日期 資料週期    郵遞區號        機關代碼                    電子郵件       行動電話            市話  縣市別代碼    行政區域代碼
0           0  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_男  5246  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
1           1  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)        大學校院(大學)_普通科_女  5538  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
2           2  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_男  4010  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
3           3  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  大學校院(大學)_專業群科(職業科)_女  3759  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000
4           4  臺中市  高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)       大學校院(大學)_綜合高中_男   151  2024-08-01T00:00:00   學年  407610  387000000A  oddisp@taichung.gov.tw  910289111  (04)22289111  66000  10019000


 schema_tool
model:  已了解數據結構。共有 4 個 CSV 檔案（2021-2024 年），涵蓋臺中市高級中等學校應屆畢業生升學就業概況。現在進行數據分析。 [{'name': 'pandas_tool', 'args': {'input': {'files': ['2021_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2022_08_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2023學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv', '2024學年度_10414-00-01-2_臺中市高級中等學校應屆畢業生升學就業概況.csv'], 'user_query': '分析台中市學生數量從2021年到2024年的變化。請先查看每個檔案的「項目」欄位有哪些不同類別，然後針對所有類別（特別是畢業生總數相關的）進行年度比較，計算各年度的總學生/畢業生數量，以及各類別的逐年變化趨勢。'}}, 'id': 'f0ad9cba-14b2-4278-9cd8-76e2b3e77786', 'type': 'tool_call'}]
tools:  === 所有檔案中「項目」欄位的唯一類別 ===
['高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)']

=== 各類別各年度總數 ===
年份                            2021   2022   2023   2024
項目
高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  25041  24327  23461  23181

=== 各類別逐年變化 (相較前一年增減) ===
年份                           2021  2022  2023  2024
項目
高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)   NaN  -714  -866  -280

=== 畢業生總數相關類別 (若存在) ===
各年度畢業生總數:
年份
2021    25041
2022    24327
2023    23461
2024    23181
Name: 數值, dtype: int64
逐年變化:
年份
2021      NaN
2022   -714.0
2023   -866.0
2024   -280.0
Name: 數值, dtype: float64
 pandas_tool
model:  分析結果已出。現在生成文字報告。 [{'name': 'report_tool', 'args': {'input': {'analysis_result': "=== 所有檔案中「項目」欄位的唯一類別 ===\n['高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)']\n\n=== 各類別各年度總數 ===\n年份                            2021   2022   2023   2024\n項目                                                     \n高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)  25041  24327  23461  23181\n\n=== 各類別逐年變化 (相較前一年增減) ===\n年份                           2021  2022  2023  2024\n項目                                                 \n高級中等學校應屆畢業生升學就業概況-畢業生(單位:人)   NaN  -714  -866  -280\n\n=== 畢業生總數相關類別 (若存在) ===\n各年度畢業生總數:\n年份\n2021    25041\n2022    24327\n2023    23461\n2024    23181\nName: 數值, dtype: int64\n逐年變化:\n年份\n2021      NaN\n2022   -714.0\n2023   -866.0\n2024   -280.0\nName: 數值, dtype: float64", 'requirement': '分析台中市學生數量從2021年到2024年的變化，並生成 Word 報告'}}, 'id': 'ae3ae82b-2ce4-47a4-a4f0-c0b63773e7f9', 'type': 'tool_call'}]
tools:  台中市高級中等學校應屆畢業生人數變化分析報告（2021－2024年）

摘要
本報告旨在分析台中市高級中等學校應屆畢業生人數於2021年至2024年間的變化趨勢。根據數據顯示，畢業生總數呈現逐年遞減的現象，自2021年的25,041人下降至2024年的23,181人，四年間累計減少1,860人。以下將就各年度數據及逐年變化進行說明，並提出初步結論。

分析內容
一、各年度畢業生總數
數據顯示，台中市高級中等學校應屆畢業生人數如下：
- 2021年：25,041人
- 2022年：24,327人
- 2023年：23,461人
- 2024年：23,181人

二、逐年變化情形
與前一年度相較，各年度增減人數為：
- 2022年較2021年減少714人
- 2023年較2022年減少866人
- 2024年較2023年減少280人

整體而言，四年間畢業生總數由25,041人降至23,181人，共計減少1,860人，減幅約7.43%。其中以2023年的年減人數最多（866人），2024年減幅雖有趨緩，但仍維持下降趨勢。

結論
根據2021年至2024年之數據，台中市高級中等學校應屆畢業生人數呈現持續下滑的態勢，每年均較前一年度減少，四年累計減少近兩千人。此一趨勢反映出畢業生總量正逐步縮減，值得相關單位持續關注。 report_tool
model:  報告已生成，現在進行 Word 排版。 [{'name': 'word_format_tool', 'args': {'input': {'output_path': 'report_output.docx', 'report': '台中市高級中等學校應屆畢業生人數變化分析報告（2021－2024年）\n\n摘要\n本報告旨在分析台中市高級中等學校應屆畢業生人數於2021年至2024年間的變化趨勢。根據數據顯示，畢業生總數呈現逐年遞減的現象，自2021年的25,041人下降至2024年的23,181人，四年間累計減少1,860人。以下將就各年度數據及逐年變化進行說明，並提出初步結論。\n\n分析內容\n一、各年度畢業生總數\n數據顯示，台中市高級中等學校應屆畢業生人數如下：\n- 2021年：25,041人\n- 2022年：24,327人\n- 2023年：23,461人\n- 2024年：23,181人\n\n二、逐年變化情形\n與前一年度相較，各年度增減人數為：\n- 2022年較2021年減少714人\n- 2023年較2022年減少866人\n- 2024年較2023年減少280人\n\n整體而言，四年間畢業生總數由25,041人降至23,181人，共計減少1,860人，減幅約7.43%。其中以2023年的年減人數最多（866人），2024年減幅雖有趨緩，但仍維持下降趨勢。\n\n結論\n根據2021年至2024年之數據，台中市高級中等學校應屆畢業生人數呈現持續下滑的態勢，每年均較前一年度減少，四年累計減少近兩千人。此一趨勢反映出畢業生總量正逐步縮減，值得相關單位持續關注。'}}, 'id': '9fb1076d-c2b7-40d6-bb7a-eb3a06af4bb3', 'type': 'tool_call'}]
tools:  Word 文件已成功生成並儲存至 report_output.docx
 word_format_tool
model:  Word 文件已成功生成！以下是完整的分析流程總結：

---

## 📊 分析流程回顧

| 步驟 | 工具 | 結果 |
|------|------|------|
| **1. 讀取結構** | `schema_tool` | 確認 4 個 CSV 檔案（2021-2024），結構一致，共 14 欄 |
| **2. 數據分析** | `pandas_tool` | 計算各年度畢業生總數及逐年變化 |
| **3. 生成報告** | `report_tool` | 產出結構化文字報告 |
| **4. 排版輸出** | `word_format_tool` | ✅ 成功生成 `report_output.docx` |

---

## 🔑 核心發現

| 年度 | 畢業生總數 | 年增減 |
|------|-----------|--------|
| 2021 | **25,041** | — |
| 2022 | **24,327** | -714 |
| 2023 | **23,461** | -866 |
| 2024 | **23,181** | -280 |

- 📉 四年累計減少 **1,860 人**，減幅約 **7.43%**
- 2023 年降幅最大（-866 人），2024 年降幅趨緩但仍持續下滑

Word 報告文件 `report_output.docx` 已儲存，可直接下載使用。 []